server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=todoapp;trustServerCertificate=true
    username: sa
    password: 123456

  datasource-secondary:
    url: jdbc:sqlserver://localhost:1433;databaseName=todoapp;trustServerCertificate=true
    username: sa
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect